name: 'Kotlin main kts runner'
description: 'Run the given code as a main.kts script'
inputs:
  script:
    description: 'Kotlin code to run'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
